Escrow/Controllers/TransactionRequestsController.cs
using Escrow.ApiRequests;
using Escrow.ApiResponses;
using Escrow.Enums;
using Escrow.Helpers;
using Escrow.Infrastructure;
using Escrow.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Configuration;
using System.Dynamic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Escrow.Controllers
{
    public class TransactionRequestsController : BaseController
    {
        // GET: TransactionRequests

        const int rate = 100;

        private string baseUrl = ConfigurationManager.AppSettings["BaseUrl"];
        EscrowModel escrowModel = new EscrowModel();
        public async Task<ActionResult> Index()
        {

            DateTime dateFrom = DateTime.Today;
            DateTime dateTo = DateTime.Today;

            List<TransactionRequest> transactions = await TransactionRequestsList(dateFrom, dateTo);

            transactions.ForEach(a => a.LocalDate = UtilityManager.Utility.FormalizeTranscationDate(a.TransactionDate, a.TransactionTime));

            transactions.ForEach(a => a.NetAmount = a.NetAmount / rate);


            escrowModel.TransactionRequests = transactions;

            transactions = transactions.OrderByDescending(a => a.DisplayDate).ToList();

            return View(escrowModel);
        }

        [HttpGet]
        public async Task<ActionResult> SettleDisputedTransaction(Guid id)
        {
            await this.CheckIfBearerTokenIsSet();

            var Client = ClientHelper.GetClient(_bearer);

            TransactionRequest transactionRequest = new TransactionRequest();

            TransactionsRequestsResponseBody TransactionsRequestsResponseBody = new TransactionsRequestsResponseBody();


            try
            {
                HttpResponseMessage response = await Client.GetAsync(
              "/api/Transaction/GetTransactionById/" + id);

                ViewBag.Disputes = DisputeCategorySelectListItems(string.Empty);

                JObject value = JObject.Parse(response.Content.ReadAsStringAsync().Result);

                TransactionsRequestsResponseBody = value.ToObject<TransactionsRequestsResponseBody>();

                transactionRequest = TransactionsRequestsResponseBody.data.FirstOrDefault();

            }
            catch (Exception ex)
            {
                return RedirectToAction("index");
            }

            return View(transactionRequest);
        }

        public async Task<ActionResult> SettleDisputedTransaction(TransactionRequest transactionRequest)
        {
            return View();
        }

        [NonAction]
        public async Task<List<TransactionRequest>> TransactionRequestsList(DateTime dateFrom, DateTime dateTo)
        {


            await this.CheckIfBearerTokenIsSet();

            var Client = ClientHelper.GetClient(_bearer);

            TransactionsRequestsResponseBody TransactionsRequestsResponseBody = new TransactionsRequestsResponseBody();

            List<TransactionRequest> result = new List<TransactionRequest>();
            try
            {
                TransactionsRangeFilterRequest tranrequest = new TransactionsRangeFilterRequest();

                tranrequest.DateFrom = dateFrom;

                tranrequest.DateTo = dateTo;

                string json = JsonConvert.SerializeObject(tranrequest);

                HttpContent _Body = new StringContent(json);

                _Body.Headers.ContentType = new MediaTypeHeaderValue("application/json");

                HttpResponseMessage response = await Client.PostAsync(
               "api/Transaction/GetTransactionsByDate", _Body);

                JObject value = JObject.Parse(response.Content.ReadAsStringAsync().Result);

                TransactionsRequestsResponseBody = value.ToObject<TransactionsRequestsResponseBody>();

                result = TransactionsRequestsResponseBody.data;

                return result;


            }
            catch (Exception e)
            {
                return new List<TransactionRequest>();

            }

        }

        [HttpPost]
        public async Task<ActionResult> FilterTransactions([Bind]B2CModelFilter b2CModelFilter)
        {

            if (string.IsNullOrEmpty(b2CModelFilter.DateFrom) && string.IsNullOrEmpty(b2CModelFilter.MsisdnOrEmail))
            {
                TempData["Error"] = "Invalid dates selected";

                return RedirectToAction("Index");
            }

            List<TransactionRequest> transactionRequests = new List<TransactionRequest>();



            if (!string.IsNullOrEmpty(b2CModelFilter.MsisdnOrEmail))
            {
                transactionRequests = await TransactionByReferenceLookup(b2CModelFilter.MsisdnOrEmail);
            }
            else
            {
                DateTime dateFrom = DateTime.ParseExact(b2CModelFilter.DateFrom, "dd/MM/yyyy", CultureInfo.InvariantCulture);
                DateTime dateTo = DateTime.ParseExact(b2CModelFilter.DateTo, "dd/MM/yyyy", CultureInfo.InvariantCulture);

                transactionRequests = await TransactionRequestsList(dateFrom, dateTo);

            }


            if (transactionRequests == null || transactionRequests.Count <= 0)
            {
                TempData["Error"] = "Unable to locate transactions from the selected dates";

                return RedirectToAction("Index");
            }

            try
            {
                transactionRequests.ForEach(a => a.NetAmount = a.NetAmount / rate);
            }
            catch (Exception)
            {

                transactionRequests = new List<TransactionRequest>();
                TempData["Error"] = "Unable to locate transaction(s)";

            }

            if (transactionRequests.Count > 0)
            {
                transactionRequests = transactionRequests.OrderByDescending(a => a.DisplayDate).ToList();
            }

            escrowModel.TransactionRequests = transactionRequests;
            return View("Index", escrowModel);

        }

        [HttpGet]
        public async Task<ActionResult> GetTransactionDetailsByReference(string reference)
        {

            await this.CheckIfBearerTokenIsSet();

            var Client = ClientHelper.GetClient(_bearer);
            TransactionRequest queryModel = new TransactionRequest();
            string fullUrl = string.Format("{0}{1}", baseUrl, "");

            dynamic postData = new ExpandoObject();
            postData.transactionReference = reference;


            string json = JsonConvert.SerializeObject(postData);

            HttpContent _Body = new StringContent(json);

            _Body.Headers.ContentType = new MediaTypeHeaderValue("application/json");

            HttpResponseMessage response = await Client.PostAsync(
                "api/Transaction/GetTransactionByReference", _Body);

            JObject value = JObject.Parse(response.Content.ReadAsStringAsync().Result);

            MasterTransactionQueryModel masterTransactionQueryModel = value.ToObject<MasterTransactionQueryModel>();

            List<TransactionRequest> result = masterTransactionQueryModel.data;


            result.Add(queryModel);

            result.ForEach(a => a.NetAmount = a.NetAmount / rate);


            escrowModel.TransactionRequests = result;

            return View("Index", escrowModel);


        }

        public async Task<ActionResult> DisputedTransaction(string reference)
        {

            List<TransactionRequest> transactionRequests = await TransactionByReferenceLookup(reference);



            transactionRequests.ForEach(a => a.NetAmount = a.NetAmount / rate);

            TransactionRequest transactionRequest = transactionRequests.FirstOrDefault();


            escrowModel.DisputeResolutionMethods = GetEnumListItemsAsync<DisputeResolutionMethods>();

            escrowModel.TransactionRequest = transactionRequest;

            escrowModel.DisputeResolutionMethod = new DisputeResolutionMethod();

            return View("DisputedTransaction", escrowModel);
        }
        public List<SelectListItem> GetEnumListItemsAsync<T>()
        {
            List<T> values = Enum.GetValues(typeof(T)).Cast<T>().ToList();

            int totalItems = values.Count;
            List<SelectListItem> selectList = new List<SelectListItem>();
            for (int i = 0; i < totalItems; i++)
            {
                selectList.Add(new SelectListItem
                {
                    Value = Convert.ToInt32(values[i]).ToString(),
                    Text = values[i].ToString(),
                });
            }

            return selectList;
        }


        public async Task<ActionResult> ResolveTransaction([Bind]DisputeResolutionMethod disputeResolutionMethod)
        {


            if (!ModelState.IsValid)
            {
                TempData["Error"] = string.Join("|", ModelState.Select(a => a.Value).SelectMany(a => a.Errors.Select(b => b.ErrorMessage)));

                return RedirectToAction("Index");
            }

            string transactionId = Request["transactionId"];
            string transactionReference = Request["reference"];
            disputeResolutionMethod.TransactionId = transactionId;
            disputeResolutionMethod.TransactionReference = transactionReference;

            if (string.IsNullOrEmpty(disputeResolutionMethod.SettlementNotes))
            {

                TempData["Error"] = "Please enter settlement notes";

                return RedirectToAction("DisputedTransaction", new { reference = disputeResolutionMethod.TransactionReference });
            }

            string apiEndpoint = string.Empty;



            disputeResolutionMethod.TransactionReference = transactionReference;
            switch (disputeResolutionMethod.ResolutionMethod)
            {

Escrow/Views/TransactionRequests/DisputedTransaction.cshtml
@model Escrow.Models.EscrowModel
@{
    ViewBag.Title = "DisputedTransaction";
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
    $(document).ready(function () {



        $("#resolutionMethod").change(function () {

            var selectedValue = $(this).val();

            if (selectedValue == "3") {
                $(".divHide").show();
            }
            else {
                $(".divHide").hide();
            }
        });


    });
</script>
<style>
    .divHide {
        display: none
    }
</style>
<div class="ibox-content m-b-sm border-bottom">

    @if (TempData["Error"] != null)
    {
        <div class="alert alert-danger fade in">
            <button class="close" data-dismiss="alert">
                ×
            </button>
            <i class="fa-fw fa fa-times"></i>
            <strong>Error!</strong> @TempData["Error"]
        </div>
    }
    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert">
                ×
            </button>
            <i class="fa-fw fa fa-check"></i>
            <strong>Success</strong> @TempData["Success"]
        </div>
    }

    @using (Html.BeginForm("ResolveTransaction", "TransactionRequests"))
    {
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group" id="data_1">
                    <label class="font-normal">Sender</label>
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.LabelFor(a => a.TransactionRequest.PayerToken, Model.TransactionRequest.PayerToken, new { @class = "form-control", disabled = "disabled" })
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group" id="data_1">
                    <label class="font-normal">Recepient</label>
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.LabelFor(a => a.TransactionRequest.PayeeToken, Model.TransactionRequest.PayeeToken, new { @class = "form-control", disabled = "disabled" })
                    </div>
                </div>
            </div>

            <div class="col-sm-4">
                <div class="form-group" id="data_1">
                    <label class="font-normal">Transaction Reference</label>
                    <div class="input-group text">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.LabelFor(a => a.TransactionRequest.TransactionReference, Model.TransactionRequest.TransactionReference, new { @class = "form-control", disabled = "disabled" })
                    </div>
                </div>
            </div>

            <div class="col-sm-4">
                <div class="form-group" id="data_1">
                    <label class="font-normal">Net Amount</label>
                    <div class="input-group text">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.LabelFor(a => a.TransactionRequest.NetAmount, Model.TransactionRequest.NetAmount.ToString(), new { @class = "form-control", disabled = "disabled", autocomplete = "sdderre", id = "" })
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group" id="data_1">
                    <label class="font-normal">Transaction Date</label>
                    <div class="input-group text">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.LabelFor(a => a.TransactionRequest.TransactionDate, $"{Model.TransactionRequest.TransactionDate} {Model.TransactionRequest.TransactionTime}", new { @class = "form-control", disabled = "disabled", autocomplete = "sdderre", id = "" })
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group" id="data_1">
                    <label class="font-normal">Transaction Status</label>
                    <div class="input-group text">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.LabelFor(a => a.TransactionRequest.StatusDescription, Model.TransactionRequest.StatusDescription, new { @class = "form-control", disabled = "disabled", autocomplete = "sdderre", id = "" })
                    </div>
                </div>
            </div>

            @Html.HiddenFor(a => a.DisputeResolutionMethod.TransactionReference, Model.TransactionRequest.TransactionReference)




        </div>

        <div class="row">
            <div class="col-sm-4">
                <div class="form-group" id="data_1">
                    <label class="font-normal">Resolution Method</label>
                    <div class="input-group text">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.DropDownListFor(a => a.DisputeResolutionMethod.ResolutionMethod, Model.DisputeResolutionMethods, new { @class = "form-control", autocomplete = "sdderre", id = "resolutionMethod" })
                    </div>
                </div>
            </div>
            <div class="col-sm-4 divHide">
                <div class="form-group" id="data_1">
                    <label class="font-normal">Recepient Amount</label>
                    <div class="input-group text">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.TextBoxFor(a => a.DisputeResolutionMethod.PayeeAmount, new { @class = "form-control", autocomplete = "sdderre" })
                    </div>
                </div>
            </div>
            <div class="col-sm-4 divHide">
                <div class="form-group" id="data_1">
                    <label class="font-normal">Sender Amount</label>
                    <div class="input-group text">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.TextBoxFor(a => a.DisputeResolutionMethod.PayerAmount, new { @class = "form-control", autocomplete = "sdderre" })
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group" id="data_1">
                    <label class="font-normal">Comments</label>
                    <div class="input-group text">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.TextBoxFor(a => a.DisputeResolutionMethod.SettlementNotes, new { @class = "form-control", autocomplete = "sdderre" })
                    </div>
                </div>
            </div>
        </div>

        @Html.Hidden("reference", Model.TransactionRequest.TransactionReference)

        @Html.Hidden("transactionId", Model.TransactionRequest.MasterTransactionId)
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="control-label" for="date_added"></label>
                    <div class="input-group">

                        <input type="submit" value="Submit" class="btn btn-primary" />
                    </div>
                </div>


            </div>
        </div>
    }


</div>

Escrow/Views/TransactionRequests/Index.cshtml
@using Escrow.Enums
@model Escrow.Models.EscrowModel
@{
    ViewBag.Title = "Transactions";
}

<script>

    function clearFilter() {
        $("#WebFilterB2C_Search").val("");
        $("#WebFilterB2C_To").val("");
        $("#WebFilterB2C_From").val("");

    }
</script>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <ol class="breadcrumb">
            <li>
                <a href="">Transactions</a>
            </li>
            <li>
                <a>Index</a>
            </li>
            <li class="active">
                <strong>Index</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="ibox-content m-b-sm border-bottom">

    @if (TempData["Error"] != null)
    {
        <div class="alert alert-danger fade in">
            <button class="close" data-dismiss="alert">
                ×
            </button>
            <i class="fa-fw fa fa-times"></i>
            <strong>Error!</strong> @TempData["Error"]
        </div>
    }
    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert">
                ×
            </button>
            <i class="fa-fw fa fa-check"></i>
            <strong>Success</strong> @TempData["Success"]
        </div>
    }
    @using (Html.BeginForm("FilterTransactions", "TransactionRequests"))
    {
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group" id="data_1">
                    <label class="font-normal">From</label>
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.TextBoxFor(a => a.B2CModelFilter.DateFrom, new { @class = "form-control", autocomplete = "1234567WEDSD", id = "WebFilterB2C_From" })
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group" id="data_1">
                    <label class="font-normal">To</label>
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.TextBoxFor(a => a.B2CModelFilter.DateTo, new { @class = "form-control", autocomplete = "1234t5errt", id = "WebFilterB2C_To" })
                    </div>
                </div>
            </div>

            <div class="col-sm-4">
                <div class="form-group" id="data">
                    <label class="font-normal">Parameter</label>
                    <div class="input-group text">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.TextBoxFor(a => a.B2CModelFilter.MsisdnOrEmail, new { @class = "form-control", placeholder = "e.g Transaction reference", autocomplete = "sdderre", id = "WebFilterB2C_Search" })
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="control-label" for="date_added"></label>
                    <div class="input-group">

                        <input type="submit" value="Search" class="btn btn-primary" />
                        <a href="#" onclick="clearFilter();" class="">Clear Search</a>
                    </div>
                </div>


            </div>
        </div>
    }

</div>
<div class="wrapper wrapper-content animated fadeInRight">

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">

                </div>
                <div class="ibox-content">

                    <table class="table table-striped table-bordered table-hover b2cGrid" data-page-size="15">
                        <thead>
                            <tr>
                                <th>Transction Date</th>
                                <th data-hide="phone">Payment Method</th>
                                <th data-hide="phone">Amount</th>
                                <th data-hide="phone">Sender</th>
                                <th data-hide="phone,tablet">Recepient</th>
                                <th data-hide="phone">Status</th>
                                <th data-hide="phone">Reference</th>


                                <th data-hide="phone">Actions</th>

                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int totalItems = Model.TransactionRequests.Count;
                            }



                            @for (int x = 0; x < totalItems; x++)
                            {

                                <tr>
                                    <td>
                                        @Model.TransactionRequests[x].DisplayDate.ToString("dd/MM/yyyy hh:mm")
                                    </td>
                                    <td>
                                        @Model.TransactionRequests[x].PaymentMethodDescription
                                    </td>
                                    <td>
                                        @Model.TransactionRequests[x].NetAmount
                                    </td>
                                    <td>
                                        @Model.TransactionRequests[x].PayerToken
                                    </td>
                                    <td>
                                        @Model.TransactionRequests[x].PayeeToken
                                    </td>
                                    <td>
                                        @Model.TransactionRequests[x].StatusDescription
                                    </td>
                                    <td>
                                        @Model.TransactionRequests[x].TransactionReference


                                    </td>
                                    <td class="text-right">
                                        @if (Model.TransactionRequests[x].Status == (byte)TransactionStatus.Disputed)
                                        {
                                            <a href="@Url.Action("DisputedTransaction","TransactionRequests",new { reference=Model.TransactionRequests[x].TransactionReference})">Resolve</a>

                                        }

                                    </td>



                                </tr>
                            }

                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="8">
                                    <ul class="pagination pull-right"></ul>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

@section Styles {
    @Styles.Render("~/plugins/awesomeCheckboxStyles")
    @Styles.Render("~/plugins/clockpickerStyles")
    @Styles.Render("~/plugins/dateRangeStyles")
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
    @Styles.Render("~/Content/plugins/chosen/chosenStyles")
    @Styles.Render("~/plugins/switcheryStyles")
    @Styles.Render("~/plugins/jasnyBootstrapStyles")
    @Styles.Render("~/plugins/nouiSliderStyles")
    @Styles.Render("~/plugins/dataPickerStyles")
    @Styles.Render("~/Content/plugins/ionRangeSlider/ionRangeStyles")
    @Styles.Render("~/plugins/imagecropperStyles")
    @Styles.Render("~/Content/plugins/colorpicker/colorpickerStyles")
    @Styles.Render("~/plugins/select2Styles")
    @Styles.Render("~/plugins/touchSpinStyles")
    @Styles.Render("~/plugins/tagInputsStyles")
    @Styles.Render("~/plugins/duallistStyles")
    @Styles.Render("~/Content/plugins/dataTables/dataTablesStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/dataPicker")
    @Scripts.Render("~/plugins/imagecropper")
    @Scripts.Render("~/plugins/dateRange")
    @Scripts.Render("~/plugins/dataTables")



    <script type="text/javascript">
        $(document).ready(function () {


            $('.b2cGrid').DataTable({
                "bDestroy": true,
                pageLength: 25,
                dom: '<"html5buttons"B>lTfgitp',
                order: [[0, "desc"]],

                buttons: [
                    { extend: 'copy' },
                    { extend: 'csv' },
                    { extend: 'excel', title: 'Transactions' },
                    { extend: 'pdf', title: 'Transactions' },

                    {
                        extend: 'print',
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                        }
                    }
                ]

            });



            var $image = $(".image-crop > img")
            $($image).cropper({
                aspectRatio: 1.618,
                preview: ".img-preview",
                done: function (data) {
                    // Output the result data for cropping image.
                }
            });



            $('#data_1 .input-group.date').datepicker({
                todayBtn: "linked",
                keyboardNavigation: false,
                forceParse: false,
                calendarWeeks: true,
                autoclose: true
            });

            $('#data_2 .input-group.date').datepicker({
                startView: 1,
                todayBtn: "linked",
                keyboardNavigation: false,
                forceParse: false,
                autoclose: true
            });

            $('#data_3 .input-group.date').datepicker({
                startView: 2,
                todayBtn: "linked",
                keyboardNavigation: false,
                forceParse: false,
                autoclose: true
            });

            $('#data_4 .input-group.date').datepicker({
                minViewMode: 1,
                keyboardNavigation: false,
                forceParse: false,
                autoclose: true,
                todayHighlight: true
            });

            $('#data_5 .input-daterange').datepicker({
                keyboardNavigation: false,
                forceParse: false,
                autoclose: true
            });





            $('input[name="daterange"]').daterangepicker();


            $('#reportrange').daterangepicker({
                format: 'dd/mm/yyyy',
                dateLimit: { days: 30 },
                showDropdowns: true,
                showWeekNumbers: true,
                timePicker: false,
                timePickerIncrement: 1,
                timePicker12Hour: true,

                opens: 'right',
                drops: 'down',
                buttonClasses: ['btn', 'btn-sm'],
                applyClass: 'btn-primary',
                cancelClass: 'btn-default',
                separator: ' to ',
                locale: {
                    applyLabel: 'Submit',
                    cancelLabel: 'Cancel',
                    fromLabel: 'From',
                    toLabel: 'To',
                    customRangeLabel: 'Custom',
                    daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                    monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                    firstDay: 1
                }
            }, function (start, end, label) {
                console.log(start.toISOString(), end.toISOString(), label);
                $('#reportrange span').html(start.format('d MM, YYYY') + ' - ' + end.format('D MM, YYYY'));
            });





        })

    </script>
}