Escrow/Controllers/CustomersController.cs
using Escrow.ApiRequests;
using Escrow.ApiResponses;
using Escrow.Helpers;
using Escrow.Infrastructure;
using Escrow.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Configuration;
using System.Dynamic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Escrow.Controllers
{


    [Authorize]
    public class CustomersController : BaseController
    {

        string baseUrl = ConfigurationManager.AppSettings["BaseUrl"];
        EscrowModel escrowModel = new EscrowModel();
        // GET: Customers

        public ActionResult Index()
        {
            escrowModel.WebFilter = new WebFilter();
            escrowModel.Customers = new List<CustomersDto>();
            return View(escrowModel);
        }

        [HttpPost]
        public async Task<ActionResult> Search([Bind]WebFilter webFilter)
        {

            List<CustomersDto> customers = new List<CustomersDto>();
            if (string.IsNullOrEmpty(webFilter.DateFrom) && string.IsNullOrEmpty(webFilter.MsisdnOrEmail))
            {
                TempData["Error"] = "Invalid dates selected";

                return RedirectToAction("Index");
            }


            if (!string.IsNullOrEmpty(webFilter.MsisdnOrEmail))
            {
                List<CustomersDto> result = new List<CustomersDto>();
                CustomersApiResponse customerData = new CustomersApiResponse();

                string url = string.Format("{0}{1}{2}", baseUrl, "api/User/GetUserByMsisdnOrEmail/", webFilter.MsisdnOrEmail);

                var apiResult = await ClientHelper.ProcessGetRequest(url);

                JObject value = JObject.Parse(apiResult);

                customerData = value.ToObject<CustomersApiResponse>();

                customers = customerData.data;


            }
            else
            {
                DateTime dateFrom = DateTime.ParseExact(webFilter.DateFrom, "dd/MM/yyyy", CultureInfo.InvariantCulture);
                DateTime dateTo = DateTime.ParseExact(webFilter.DateTo, "dd/MM/yyyy", CultureInfo.InvariantCulture);


                customers = await GetUsers(dateFrom, dateTo);
            }


            if (customers == null || customers.Count <= 0)
            {
                customers = new List<CustomersDto>();

                TempData["Error"] = "Unable to locate customers from the specified dates";

                escrowModel.Customers = customers;

                return View("Index", escrowModel);

            }


            customers = customers.OrderByDescending(a => a.DateCreated).ToList();


            escrowModel.Customers = customers;

            return View("Index", escrowModel);
        }


        public async Task<ActionResult> Edit(Guid id)
        {
            List<CustomersDto> result = new List<CustomersDto>();
            CustomersApiResponse customerData = new CustomersApiResponse();

            string url = string.Format("{0}{1}{2}", baseUrl, "/api/User/GetUser/", id);

            var apiResult = await ClientHelper.ProcessGetRequest(url);

            JObject value = JObject.Parse(apiResult);

            customerData = value.ToObject<CustomersApiResponse>();


            CustomersDto customer = customerData.data.FirstOrDefault();

            escrowModel.UpdateModel = new UpdateModel
            {
                FirstName = customer.FirstName,
                LastName = customer.LastName,
                Msisdn = customer.Msisdn,
                UserId = customer.UserId
            };

            return View("Edit", escrowModel);
        }

        [NonAction]
        public async Task<List<CustomersDto>> GetUsers(DateTime dateFrom, DateTime dateTo)
        {


            await this.CheckIfBearerTokenIsSet();

            var Client = ClientHelper.GetClient(_bearer);

            CustomersApiResponse customersApiResponse = new CustomersApiResponse();

            List<CustomersDto> result = new List<CustomersDto>();
            try
            {
                TransactionsRangeFilterRequest tranrequest = new TransactionsRangeFilterRequest();

                tranrequest.DateFrom = dateFrom;

                tranrequest.DateTo = dateTo;

                string json = JsonConvert.SerializeObject(tranrequest);

                HttpContent _Body = new StringContent(json);

                _Body.Headers.ContentType = new MediaTypeHeaderValue("application/json");

                HttpResponseMessage response = await Client.PostAsync(
                    "api/User/GetPlatformUsers", _Body);

                JObject value = JObject.Parse(response.Content.ReadAsStringAsync().Result);

                customersApiResponse = value.ToObject<CustomersApiResponse>();

                customersApiResponse.data = customersApiResponse.data.OrderByDescending(a => a.DateCreated).ToList();

                result = customersApiResponse.data;
               


                return result;


            }
            catch (Exception e)
            {
                return new List<CustomersDto>();

            }

        }

        //[HttpPost]
        //public async Task<JsonResult> CustomersRequestsList(JQueryDataTablesModel datatablemodel)
        //{

        //    var pagecollection = await GetUsers();

        //    int totalRecordCount = 0;

        //    int searchRecordCount = 0;

        //    var customers = GetAllUsers(startIndex: datatablemodel.iDisplayStart,
        //        pageSize: datatablemodel.iDisplayLength, sortedColumns: datatablemodel.GetSortedColumns(),
        //        totalRecordCount: out totalRecordCount, searchRecordCount: out searchRecordCount, searchString: datatablemodel.sSearch, customers: pagecollection);

        //    return Json(new JQueryDataTablesResponse<CustomersDto>(items: customers,
        //        totalRecords: totalRecordCount,
        //        totalDisplayRecords: searchRecordCount,
        //        sEcho: datatablemodel.sEcho));
        //}

        [NonAction]
        public static IList<CustomersDto> GetAllUsers(int startIndex, int pageSize, ReadOnlyCollection<SortedColumn> sortedColumns, out int totalRecordCount, out int searchRecordCount, string searchString, IList<CustomersDto> customers)
        {
            var data = customers;
            totalRecordCount = data.Count();

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                data = customers.Where(c => c.FirstName
                    .ToLower().Contains(searchString.ToLower()) ||
                    c.LastName.ToLower().Contains(searchString.ToLower()) ||
                    c.IsActive.ToString().ToLower().Contains(searchString.ToLower()) ||
                    c.Msisdn.ToLower().Contains(searchString.ToLower())).ToList();
            }

            searchRecordCount = data.Count;

            IOrderedEnumerable<CustomersDto> sortedTrans = null;

            foreach (var sortedColumn in sortedColumns)
            {
                switch (sortedColumn.PropertyName)
                {
                    case "FirstName":
                        sortedTrans = sortedTrans == null ? data.CustomSort(sortedColumn.Direction, tran => tran.FirstName)
                            : sortedTrans.CustomSort(sortedColumn.Direction, tran => tran.FirstName);
                        break;

                    case "LastName":
                        sortedTrans = sortedTrans == null ? data.CustomSort(sortedColumn.Direction, tran => tran.LastName)
                            : sortedTrans.CustomSort(sortedColumn.Direction, tran => tran.LastName);
                        break;
                    case "Msisdn":
                        sortedTrans = sortedTrans == null ? data.CustomSort(sortedColumn.Direction, tran => tran.Msisdn)
                            : sortedTrans.CustomSort(sortedColumn.Direction, tran => tran.Msisdn);
                        break;
                    case "FormatedDate":
                        sortedTrans = sortedTrans == null ? data.CustomSort(sortedColumn.Direction, tran => tran.DateCreated)
                            : sortedTrans.CustomSort(sortedColumn.Direction, tran => tran.DateCreated);
                        break;

                }


            }

            return sortedTrans.Skip(startIndex).Take(pageSize).ToList();
        }

        public async Task<ActionResult> BlackListUser([Bind]UpdateModel updateModel)
        {
            if (!ModelState.IsValid)
            {

                TempData["Error"] = string.Join(" |", ModelState.Select(a => a.Value.Errors.Select(b => b.ErrorMessage)));

                return RedirectToAction("Index");
            }

            var Client = ClientHelper.GetClient(_bearer);

            dynamic postData = new ExpandoObject();
            postData.black_list_by = User.Identity.Name;
            postData.user_id = updateModel.UserId;
            postData.reason = updateModel.BlackListReason;

            string data = JsonConvert.SerializeObject(postData);

            HttpContent _Body = new StringContent(data);

            _Body.Headers.ContentType = new MediaTypeHeaderValue("application/json");

            HttpResponseMessage response = await Client.PostAsync(
                "/api/User/DisableClientService", _Body);

            JObject value = JObject.Parse(response.Content.ReadAsStringAsync().Result);

            BlacklistResponseDto customerData = value.ToObject<BlacklistResponseDto>();

            if (customerData.status?.code == Convert.ToInt32(HttpStatusCode.InternalServerError).ToString())
            {
                TempData["Error"] = customerData.status.message;
            }
            else
            {
                TempData["Success"] = customerData.status.message;

            }


            return RedirectToAction("Index");

Escrow/Views/Customers/Edit.cshtml
@model Escrow.Models.EscrowModel
@{
    ViewBag.Title = "Edit";
}

<div class="ibox-content m-b-sm border-bottom">

    @using (Html.BeginForm("BlackListUser", "Customers"))
    {
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group" id="data_1">
                    <label class="font-normal">From</label>
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.TextBoxFor(a => a.UpdateModel.FirstName, new { @class = "form-control", autocomplete = "232322dwdw", id = "WebFilter_From" })
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group" id="data_1">
                    <label class="font-normal">To</label>
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.TextBoxFor(a => a.UpdateModel.LastName, new { @class = "form-control", autocomplete = "sdderre", id = "WebFilter_To" })
                    </div>
                </div>
            </div>

            <div class="col-sm-4">
                <div class="form-group" id="data_1">
                    <label class="font-normal">Blacklist Reason</label>
                    <div class="input-group text">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.TextAreaFor(a => a.UpdateModel.BlackListReason, new { @class = "form-control", autocomplete = "sdderre", id = "" })
                    </div>
                </div>
            </div>

            @Html.HiddenFor(a => a.UpdateModel.UserId)



        </div>

        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="control-label" for="date_added"></label>
                    <div class="input-group">

                        <input type="submit" value="Submit" class="btn btn-primary" />
                    </div>
                </div>


            </div>
        </div>
    }

</div>

Escrow/Views/Customers/Index.cshtml
@model Escrow.Models.EscrowModel
@{
    ViewBag.Title = "Customers";
}

<script>

    function clearFilter() {
        $("#WebFilter_Search").val("");
        $("#WebFilter_To").val("");
        $("#WebFilter_From").val("");

    }
</script>


<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <ol class="breadcrumb">
            <li>
                <a href="c">Customers</a>
            </li>
            <li>
                <a>Users</a>
            </li>
            <li class="active">
                <strong>Index</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="ibox-content m-b-sm border-bottom">

    @if (TempData["Error"] != null)
    {
        <div class="alert alert-danger fade in">
            <button class="close" data-dismiss="alert">
                ×
            </button>
            <i class="fa-fw fa fa-times"></i>
            <strong>Error!</strong> @TempData["Error"]
        </div>
    }
    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert">
                ×
            </button>
            <i class="fa-fw fa fa-check"></i>
            <strong>Success</strong> @TempData["Success"]
        </div>
    }
    @using (Html.BeginForm("Search", "Customers"))
    {
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group" id="data_1">
                    <label class="font-normal">From</label>
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.TextBoxFor(a => a.WebFilter.DateFrom, new { @class = "form-control", autocomplete = "232322dwdw", id = "WebFilter_From" })
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group" id="data_1">
                    <label class="font-normal">To</label>
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.TextBoxFor(a => a.WebFilter.DateTo, new { @class = "form-control", autocomplete = "sdderre", id = "WebFilter_To" })
                    </div>
                </div>
            </div>

            <div class="col-sm-4">
                <div class="form-group" id="data_1">
                    <label class="font-normal">Parameter</label>
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.TextBoxFor(a => a.WebFilter.MsisdnOrEmail, new { @class = "form-control", autocomplete = "sdderre", placeholder = "phone or email", id = "WebFilter_Search" })
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="control-label" for="date_added"></label>
                    <div class="input-group">

                        <input type="submit" value="Search" class="btn btn-primary" />
                        <a href="#" onclick="clearFilter();" class="">Clear Search</a>
                    </div>
                </div>


            </div>
        </div>
    }

</div>
<div class="wrapper wrapper-content animated fadeInRight">


    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">

                </div>
                <div class="ibox-content">

                    <table class="table table-striped table-bordered table-hover usersGrid" data-page-size="15">
                        <thead>
                            <tr>
                                <th>Created Date</th>
                                <th data-hide="phone">First Name</th>
                                <th data-hide="phone">Last Name</th>
                                <th data-hide="phone">Msisdn</th>
                                <th data-hide="phone">Email</th>
                                <th data-hide="phone,tablet">IsBlacklisted</th>
                                <th data-hide="phone">Actions</th>

                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int totalItems = Model.Customers.Count;
                            }



                            @for (int x = 0; x < totalItems; x++)
                            {

                                <tr>
                                    <td>
                                        @Model.Customers[x].DateCreated.ToString("dd/MM/yyyy hh:mm:ss")
                                    </td>
                                    <td>
                                        @Model.Customers[x].FirstName
                                    </td>
                                    <td>
                                        @Model.Customers[x].LastName
                                    </td>
                                    <td>
                                        @Model.Customers[x].Msisdn
                                    </td>
                                    <td>
                                        @Model.Customers[x].Email
                                    </td>
                                    <td>
                                        @Model.Customers[x].IsBlacklisted

                                    </td>
                                    <td class="text-right">
                                        @if (!Model.Customers[x].IsBlacklisted)
                                        {
                                            <a href="@Url.Action("Edit", "Customers", new {id = Model.Customers[x].UserId, phone = Model.Customers[x].Msisdn})" class="">Disable</a>

                                        }
                                    </td>



                                </tr>
                            }

                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="7">
                                    <ul class="pagination pull-right"></ul>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

@section Styles {
    @Styles.Render("~/plugins/awesomeCheckboxStyles")
    @Styles.Render("~/plugins/clockpickerStyles")
    @Styles.Render("~/plugins/dateRangeStyles")
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
    @Styles.Render("~/Content/plugins/chosen/chosenStyles")
    @Styles.Render("~/plugins/switcheryStyles")
    @Styles.Render("~/plugins/jasnyBootstrapStyles")
    @Styles.Render("~/plugins/nouiSliderStyles")
    @Styles.Render("~/plugins/dataPickerStyles")
    @Styles.Render("~/Content/plugins/ionRangeSlider/ionRangeStyles")
    @Styles.Render("~/plugins/imagecropperStyles")
    @Styles.Render("~/Content/plugins/colorpicker/colorpickerStyles")
    @Styles.Render("~/plugins/select2Styles")
    @Styles.Render("~/plugins/touchSpinStyles")
    @Styles.Render("~/plugins/tagInputsStyles")
    @Styles.Render("~/plugins/duallistStyles")
    @Styles.Render("~/Content/plugins/dataTables/dataTablesStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/dataPicker")
    @Scripts.Render("~/plugins/imagecropper")
    @Scripts.Render("~/plugins/dateRange")
    @Scripts.Render("~/plugins/dataTables")



    <script type="text/javascript">
        $(document).ready(function () {


            $('.usersGrid').DataTable({
                "bDestroy": true,
                pageLength: 25,
                dom: '<"html5buttons"B>lTfgitp',
                order: [[0, "desc"]],

                buttons: [
                    { extend: 'copy' },
                    { extend: 'csv' },
                    { extend: 'excel', title: 'Users' },
                    { extend: 'pdf', title: 'Users' },

                    {
                        extend: 'print',
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                        }
                    }
                ]

            });



            var $image = $(".image-crop > img")
            $($image).cropper({
                aspectRatio: 1.618,
                preview: ".img-preview",
                done: function (data) {
                    // Output the result data for cropping image.
                }
            });



            $('#data_1 .input-group.date').datepicker({
                todayBtn: "linked",
                keyboardNavigation: false,
                forceParse: false,
                calendarWeeks: true,
                autoclose: true
            });

            $('#data_2 .input-group.date').datepicker({
                startView: 1,
                todayBtn: "linked",
                keyboardNavigation: false,
                forceParse: false,
                autoclose: true
            });

            $('#data_3 .input-group.date').datepicker({
                startView: 2,
                todayBtn: "linked",
                keyboardNavigation: false,
                forceParse: false,
                autoclose: true
            });

            $('#data_4 .input-group.date').datepicker({
                minViewMode: 1,
                keyboardNavigation: false,
                forceParse: false,
                autoclose: true,
                todayHighlight: true
            });

            "aaSorting": [[0, 'desc']]
        });





            $('input[name="daterange"]').daterangepicker();


            $('#reportrange').daterangepicker({
                format: 'dd/mm/yyyy',
                dateLimit: { days: 30 },
                showDropdowns: true,
                showWeekNumbers: true,
                timePicker: false,
                timePickerIncrement: 1,
                timePicker12Hour: true,

                opens: 'right',
                drops: 'down',
                buttonClasses: ['btn', 'btn-sm'],
                applyClass: 'btn-primary',
                cancelClass: 'btn-default',
                separator: ' to ',
                locale: {
                    applyLabel: 'Submit',
                    cancelLabel: 'Cancel',
                    fromLabel: 'From',
                    toLabel: 'To',
                    customRangeLabel: 'Custom',
                    daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                    monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                    firstDay: 1
                }
            }, function (start, end, label) {
                console.log(start.toISOString(), end.toISOString(), label);
                $('#reportrange span').html(start.format('dd/mm/yyyy') + ' - ' + end.format('dd/mm/yyyy'));
            });





        })

    </script>
}