Escrow/Controllers/B2CRequestsController.cs
using Escrow.ApiRequests;
using Escrow.ApiResponses;
using Escrow.Helpers;
using Escrow.Infrastructure;
using Escrow.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Escrow.Controllers
{
    [Authorize]
    public class B2CRequestsController : BaseController
    {
        EscrowModel escrowModel = new EscrowModel();

        // GET: B2CRequests
        public async Task<ActionResult> Index()
        {

            DateTime dateFrom = DateTime.Today;
            DateTime dateTo = DateTime.Today;


            List<B2CRequest> b2CRequests = await B2CTransactionList(dateFrom, dateTo);

            escrowModel.B2CRequests = b2CRequests;
            escrowModel.B2CModelFilter = new B2CModelFilter();

            return View(escrowModel);
        }





        public async Task<ActionResult> FilterB2CRequests([Bind]B2CModelFilter b2CModelFilter)
        {

            if (string.IsNullOrEmpty(b2CModelFilter.DateFrom) || string.IsNullOrEmpty(b2CModelFilter.DateTo))
            {


                TempData["Error"] = "Invalid  dates selected";

                return RedirectToAction("Index");
            }


            DateTime dateFrom = DateTime.ParseExact(b2CModelFilter.DateFrom, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            DateTime dateTo = DateTime.ParseExact(b2CModelFilter.DateTo, "dd/MM/yyyy", CultureInfo.InvariantCulture);


            List<B2CRequest> b2CRequests = await B2CTransactionList(dateFrom, dateTo);
            if (b2CRequests.Count > 0)
            {
                b2CRequests = b2CRequests.OrderByDescending(a => a.DisplayDate).ToList();
            }

            escrowModel.B2CRequests = b2CRequests;



            return View("Index", escrowModel);

        }

        public async Task<List<B2CRequest>> B2CTransactionList(DateTime dateFrom, DateTime dateTo)
        {

            await this.CheckIfBearerTokenIsSet();

            var Client = ClientHelper.GetClient(_bearer);

            B2CRequestsResponseBody B2CRequestsResponseBody = new B2CRequestsResponseBody();

            List<B2CRequest> result = new List<B2CRequest>();
            try
            {
                TransactionsRangeFilterRequest tranrequest = new TransactionsRangeFilterRequest();
                tranrequest.DateFrom = dateFrom;
                tranrequest.DateTo = dateTo;

                string json = JsonConvert.SerializeObject(tranrequest);

                HttpContent body = new StringContent(json);

                body.Headers.ContentType = new MediaTypeHeaderValue("application/json");

                HttpResponseMessage response = await Client.PostAsync(
               "api/Transaction/GetMpesaB2CRequests", body);

                string result1 = response.Content.ReadAsStringAsync().Result;
                JObject value = JObject.Parse(response.Content.ReadAsStringAsync().Result);

                B2CRequestsResponseBody = value.ToObject<B2CRequestsResponseBody>();

                result = B2CRequestsResponseBody.data;

                return result;



            }
            catch (Exception e)
            {
                return new List<B2CRequest>();

            }

        }

        //[HttpPost]
        //public async Task<JsonResult> TransactionRequestsList(JQueryDataTablesModel datatablemodel)
        //{

        //    var pagecollection = await B2CTransactionList();

        //    int totalRecordCount = 0;

        //    int searchRecordCount = 0;

        //    var transactionList = GetAllB2CTransactions(startIndex: datatablemodel.iDisplayStart,
        //       pageSize: datatablemodel.iDisplayLength, sortedColumns: datatablemodel.GetSortedColumns(),
        //       totalRecordCount: out totalRecordCount, searchRecordCount: out searchRecordCount, searchString: datatablemodel.sSearch, TransactionList: pagecollection);

        //    return Json(new JQueryDataTablesResponse<B2CRequest>(items: transactionList,
        //       totalRecords: totalRecordCount,
        //       totalDisplayRecords: searchRecordCount,
        //       sEcho: datatablemodel.sEcho));
        //}

        [NonAction]
        public static IList<B2CRequest> GetAllB2CTransactions(int startIndex, int pageSize, ReadOnlyCollection<SortedColumn> sortedColumns, out int totalRecordCount, out int searchRecordCount, string searchString, IList<B2CRequest> TransactionList)
        {
            var transactions = TransactionList;
            totalRecordCount = transactions.Count();

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                transactions = transactions.Where(c => c.Msisdn
                    .ToLower().Contains(searchString.ToLower()) || c.MpesaCode.ToLower().Contains(searchString.ToLower())).ToList(); ;
            }

            searchRecordCount = transactions.Count;

            IOrderedEnumerable<B2CRequest> sortedTrans = null;

            foreach (var sortedColumn in sortedColumns)
            {
                switch (sortedColumn.PropertyName)
                {
                    case "Msisdn":
                        sortedTrans = sortedTrans == null ? transactions.CustomSort(sortedColumn.Direction, tran => tran.Msisdn)
                            : sortedTrans.CustomSort(sortedColumn.Direction, tran => tran.Msisdn);
                        break;

                    case "Amount":
                        sortedTrans = sortedTrans == null ? transactions.CustomSort(sortedColumn.Direction, tran => tran.Amount)
                            : sortedTrans.CustomSort(sortedColumn.Direction, tran => tran.Amount);
                        break;
                    case "MasterTransactionId":
                        sortedTrans = sortedTrans == null ? transactions.CustomSort(sortedColumn.Direction, tran => tran.MasterTransactionId)
                            : sortedTrans.CustomSort(sortedColumn.Direction, tran => tran.MasterTransactionId);
                        break;

                    case "MpesaCode":
                        sortedTrans = sortedTrans == null ? transactions.CustomSort(sortedColumn.Direction, tran => tran.MpesaCode)
                            : sortedTrans.CustomSort(sortedColumn.Direction, tran => tran.MpesaCode);
                        break;

                    case "CreateDate":
                        sortedTrans = sortedTrans == null ? transactions.CustomSort(sortedColumn.Direction, tran => tran.CreatedDate)
                            : sortedTrans.CustomSort(sortedColumn.Direction, tran => tran.CreatedDate);
                        break;
                    case "ReceiverPartyPublicName":
                        sortedTrans = sortedTrans == null ? transactions.CustomSort(sortedColumn.Direction, tran => tran.ReceiverPartyPublicName)
                            : sortedTrans.CustomSort(sortedColumn.Direction, tran => tran.CreatedDate);
                        break;

                }


            }

            return sortedTrans.Skip(startIndex).Take(pageSize).ToList();
        }
    }
}

Escrow/Views/B2CRequests/Index.cshtml
@using Escrow.Enums
@model Escrow.Models.EscrowModel
@{
    ViewBag.Title = "B2C Requests";
}

<script>

    function clearFilter() {
        $("#WebFilterB2C_Search").val("");
        $("#WebFilterB2C_To").val("");
        $("#WebFilterB2C_From").val("");

    }
</script>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <ol class="breadcrumb">
            <li>
                <a href="">B2C Request</a>
            </li>
            <li>
                <a>Index</a>
            </li>
            <li class="active">
                <strong>Index</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="ibox-content m-b-sm border-bottom">

    @using (Html.BeginForm("FilterB2CRequests", "B2CRequests"))
    {
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group" id="data_1">
                    <label class="font-normal">From</label>
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.TextBoxFor(a => a.B2CModelFilter.DateFrom, new { @class = "form-control", autocomplete = "1234567WEDSD", id = "WebFilterB2C_From" })
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group" id="data_1">
                    <label class="font-normal">To</label>
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.TextBoxFor(a => a.B2CModelFilter.DateTo, new { @class = "form-control", autocomplete = "1234t5errt", id = "WebFilterB2C_To" })
                    </div>
                </div>
            </div>

            <div class="col-sm-4">
                <div class="form-group" id="data">
                    <label class="font-normal">Parameter</label>
                    <div class="input-group text">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.TextBoxFor(a => a.B2CModelFilter.MsisdnOrEmail, new { @class = "form-control", autocomplete = "sdderre", id = "WebFilterB2C_Search" })
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label class="control-label" for="date_added"></label>
                    <div class="input-group">

                        <input type="submit" value="Search" class="btn btn-primary" />
                        <a href="#" onclick="clearFilter();" class="">Clear Search</a>
                    </div>
                </div>


            </div>
        </div>
    }

</div>
<div class="wrapper wrapper-content animated fadeInRight">

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">

                </div>
                <div class="ibox-content">

                    <table class="table table-striped table-bordered table-hover b2cGrid" data-page-size="15">
                        <thead>
                            <tr>
                                <th>Recepient</th>
                                <th data-hide="phone">Amount</th>
                                <th data-hide="phone">Status</th>
                                <th data-hide="phone">MpesaCode</th>
                                <th data-hide="phone,tablet">Transaction Date</th>
                                <th data-hide="phone">Verinet Transaction Ref</th>
                                <th data-hide="phone">Response Payload</th>


                                <th data-hide="phone">Actions</th>

                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int totalItems = Model.B2CRequests.Count;
                            }



                            @for (int x = 0; x < totalItems; x++)
                            {

                                <tr>
                                    <td>
                                        @(string.IsNullOrEmpty(Model.B2CRequests[x].ReceiverPartyPublicName) ? Model.B2CRequests[x].MasterTransactionPayeeToken : Model.B2CRequests[x].ReceiverPartyPublicName)

                                    </td>
                                    <td>
                                        @Model.B2CRequests[x].Amount
                                    </td>
                                    <td>
                                        @Model.B2CRequests[x].StatusDescription
                                    </td>
                                    <td>
                                        @Model.B2CRequests[x].MpesaCode
                                    </td>
                                    <td>
                                        @Model.B2CRequests[x].DisplayDate.ToString("dd/MM/yyyy hh:mm")
                                    </td>
                                    <td>
                                        @Model.B2CRequests[x].MasterTransactionTransactionReference
                                    </td>
                                    <td>
                                        @if (Model.B2CRequests[x].StatusDescription == B2CStatus.Failed.ToString())
                                        {
                                            @Model.B2CRequests[x].ResponseMessage

                                        }
                                    </td>
                                    <td class="text-right">
                                        <a href="@Url.Action("GetTransactionDetailsByReference", "TransactionRequests", new { reference = @Model.B2CRequests[x].MasterTransactionTransactionReference })">View Transaction</a>
                                    </td>



                                </tr>
                            }

                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="8">
                                    <ul class="pagination pull-right"></ul>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

@section Styles {
    @Styles.Render("~/plugins/awesomeCheckboxStyles")
    @Styles.Render("~/plugins/clockpickerStyles")
    @Styles.Render("~/plugins/dateRangeStyles")
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
    @Styles.Render("~/Content/plugins/chosen/chosenStyles")
    @Styles.Render("~/plugins/switcheryStyles")
    @Styles.Render("~/plugins/jasnyBootstrapStyles")
    @Styles.Render("~/plugins/nouiSliderStyles")
    @Styles.Render("~/plugins/dataPickerStyles")
    @Styles.Render("~/Content/plugins/ionRangeSlider/ionRangeStyles")
    @Styles.Render("~/plugins/imagecropperStyles")
    @Styles.Render("~/Content/plugins/colorpicker/colorpickerStyles")
    @Styles.Render("~/plugins/select2Styles")
    @Styles.Render("~/plugins/touchSpinStyles")
    @Styles.Render("~/plugins/tagInputsStyles")
    @Styles.Render("~/plugins/duallistStyles")
    @Styles.Render("~/Content/plugins/dataTables/dataTablesStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/dataPicker")
    @Scripts.Render("~/plugins/imagecropper")
    @Scripts.Render("~/plugins/dateRange")
    @Scripts.Render("~/plugins/dataTables")



    <script type="text/javascript">
        $(document).ready(function () {


            $('.b2cGrid').DataTable({
                "bDestroy": true,
                pageLength: 25,
                dom: '<"html5buttons"B>lTfgitp',
                order: [[4, "desc"]],

                buttons: [
                    { extend: 'copy' },
                    { extend: 'csv' },
                    { extend: 'excel', title: 'B2C Transactions' },
                    { extend: 'pdf', title: 'B2C Transactions' },

                    {
                        extend: 'print',
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                        }
                    }
                ]

            });



            var $image = $(".image-crop > img")
            $($image).cropper({
                aspectRatio: 1.618,
                preview: ".img-preview",
                done: function (data) {
                    // Output the result data for cropping image.
                }
            });



            $('#data_1 .input-group.date').datepicker({
                todayBtn: "linked",
                keyboardNavigation: false,
                forceParse: false,
                calendarWeeks: true,
                autoclose: true
            });

            $('#data_2 .input-group.date').datepicker({
                startView: 1,
                todayBtn: "linked",
                keyboardNavigation: false,
                forceParse: false,
                autoclose: true
            });

            $('#data_3 .input-group.date').datepicker({
                startView: 2,
                todayBtn: "linked",
                keyboardNavigation: false,
                forceParse: false,
                autoclose: true
            });

            $('#data_4 .input-group.date').datepicker({
                minViewMode: 1,
                keyboardNavigation: false,
                forceParse: false,
                autoclose: true,
                todayHighlight: true
            });

            $('#data_5 .input-daterange').datepicker({
                keyboardNavigation: false,
                forceParse: false,
                autoclose: true
            });





            $('input[name="daterange"]').daterangepicker();


            $('#reportrange').daterangepicker({
                format: 'dd/mm/yyyy',
                dateLimit: { days: 30 },
                showDropdowns: true,
                showWeekNumbers: true,
                timePicker: false,
                timePickerIncrement: 1,
                timePicker12Hour: true,

                opens: 'right',
                drops: 'down',
                buttonClasses: ['btn', 'btn-sm'],
                applyClass: 'btn-primary',
                cancelClass: 'btn-default',
                separator: ' to ',
                locale: {
                    applyLabel: 'Submit',
                    cancelLabel: 'Cancel',
                    fromLabel: 'From',
                    toLabel: 'To',
                    customRangeLabel: 'Custom',
                    daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                    monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                    firstDay: 1
                }
            }, function (start, end, label) {
                console.log(start.toISOString(), end.toISOString(), label);
                $('#reportrange span').html(start.format('d MM, YYYY') + ' - ' + end.format('D MM, YYYY'));
            });





        })

    </script>
}