Escrow/Controllers/SecurityController.cs
using Escrow.Helpers;
using Escrow.Infrastructure;
using Escrow.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Escrow.Identity;
using ApplicationUser = Escrow.Models.ApplicationUser;

namespace Escrow.Controllers
{
    [Authorize]
    public class SecurityController : Controller
    {

        private readonly RoleManager<IdentityRole> _roleManager;

        private readonly ApplicationUserManager _applicationUserManager;

        public SecurityController()
        {
            _roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>());

            _applicationUserManager = new ApplicationUserManager(new UserStore<ApplicationUser>(new Escrow.Models.ApplicationDbContext()));


        }

        public SecurityController(ApplicationUserManager userManager)
        {
            _roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>());

            _applicationUserManager = userManager;

        }


        #region Roles
        // GET: Security
        public async Task<ActionResult> Index()
        {

            return View();
        }

        [HttpPost]
        public async Task<JsonResult> Roles(JQueryDataTablesModel datatablemodel)
        {

            var pagecollection = _roleManager.Roles.ToList();

            int totalRecordCount = 0;

            int searchRecordCount = 0;

            var rolesList = GetAllRoles(startIndex: datatablemodel.iDisplayStart,
              pageSize: datatablemodel.iDisplayLength, sortedColumns: datatablemodel.GetSortedColumns(),
              totalRecordCount: out totalRecordCount, searchRecordCount: out searchRecordCount, searchString: datatablemodel.sSearch, RoleList: pagecollection);

            return Json(new JQueryDataTablesResponse<IdentityRole>(items: rolesList,
              totalRecords: totalRecordCount,
              totalDisplayRecords: searchRecordCount,
              sEcho: datatablemodel.sEcho));
        }

        [NonAction]
        public static IList<IdentityRole> GetAllRoles(int startIndex, int pageSize, ReadOnlyCollection<SortedColumn> sortedColumns, out int totalRecordCount, out int searchRecordCount, string searchString, IList<IdentityRole> RoleList)
        {
            var roles = RoleList;
            totalRecordCount = roles.Count();

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                roles = roles.Where(c => c.Name
                    .ToLower().Contains(searchString.ToLower()) || c.Id.ToLower().Contains(searchString.ToLower())).ToList(); ;
            }

            searchRecordCount = roles.Count;

            IOrderedEnumerable<IdentityRole> sortedTrans = null;

            foreach (var sortedColumn in sortedColumns)
            {
                switch (sortedColumn.PropertyName)
                {
                    case "Name":
                        sortedTrans = sortedTrans == null ? roles.CustomSort(sortedColumn.Direction, tran => tran.Name)
                            : sortedTrans.CustomSort(sortedColumn.Direction, tran => tran.Name);
                        break;


                }


            }

            return sortedTrans.Skip(startIndex).Take(pageSize).ToList();
        }

        [HttpGet]
        public async Task<ActionResult> CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> CreateRole(Roles role)
        {
            if (string.IsNullOrEmpty(role.Name))
            {
                TempData["ModelError"] = "Role Name is required";

                return View("CreateRole");
            }


            var roleCreate = new IdentityRole(role.Name);

            if (_roleManager.RoleExists(roleCreate.Name))
            {
                TempData["ModelError"] = "Role Exists Already";

                return View();
            }

            var identityResult = _roleManager.Create(roleCreate);

            if (identityResult != null)
            {
                TempData["Success"] = "Role Created Successfully";

                return RedirectToAction("Index");
            }

            return View();
        }


        [HttpGet]
        public async Task<ActionResult> EditRole(string id)
        {
            var identityResult = _roleManager.FindById(id);

            if (identityResult == null)
            {
                TempData["Error"] = "Role not found";

                return RedirectToAction("Roles");
            }

            var roles = new Roles
            {
                Id = Guid.Parse(id),
                Name = identityResult.Name
            };
            return View("editrole", roles);

        }

        [HttpPost]
        public async Task<ActionResult> EditRole(Roles role)
        {
            if (string.IsNullOrEmpty(role.Name))
            {
                TempData["Error"] = "Role name is required.";

                return RedirectToAction("Roles");
            }

            var roleUpdate = new IdentityRole
            {
                Id = role.Id.ToString(),
                Name = role.Name
            };

            var identityRole = _roleManager.FindById(roleUpdate.Id);

            if (identityRole != null)
            {
                if (identityRole.Name == role.Name)
                {
                    TempData["Success"] = "Request completed successfully.";

                    return RedirectToAction("Roles");
                }
            }
            else
            {
                TempData["Error"] = "Unable to find a role with the specified id";

                return RedirectToAction("Roles");
            }

            identityRole.Name = role.Name;

            var updateResult = _roleManager.Update(identityRole);


            var roles = new Roles { Name = role.Name, Id = role.Id };
            if (updateResult == null)
            {
                TempData["Error"] = "Role could not be updated.Please try again";

                return View("editrole", roles);
            }
            TempData["Success"] = "Role Updated Successfully";

            return RedirectToAction("Roles");

        }



        #endregion


        #region users
        [HttpGet]
        public async Task<ActionResult> CreateUser()
        {
            ViewBag.RolesList = GetUserRoleInfo(string.Empty, string.Empty);

            var userRegistration = new UserDetails { PhoneNumber = "254" };


            return View(userRegistration);
        }

        [HttpPost]
        public async Task<ActionResult> CreateUser(UserDetails userDetails)
        {
            var applicationUser = await _applicationUserManager.FindByNameAsync(User.Identity.Name);

            ViewBag.RolesList = GetUserRoleInfo(string.Empty, string.Empty);


            var userRegistration = new UserDetails { PhoneNumber = "254" };

            if (!ModelState.IsValid)
            {
                var errorMessages = string.Join(" |",
                    ModelState.Values.SelectMany(a => a.Errors).Select(a => a.ErrorMessage));

                ModelState.AddModelError("", errorMessages);

                ViewBag.ModelError = "Invalid Model State";

                return View(userDetails);
            }

            var userCheck = await _applicationUserManager.FindByEmailAsync(userDetails.Email);

            if (userCheck != null)
            {
                TempData["Error"] = "User with specified email exists already";

                return View(userDetails);
            }

            var userNameCheck = _applicationUserManager.FindByName(userDetails.UserName);

            if (userNameCheck != null)
            {
                TempData["Error"] = "User with specified username exists already";

                return View("createuser", userDetails);
            }

            var userRoles = string.Join(",", userDetails.AssignedRole);

            string status = string.Empty;

            if (_applicationUserManager.FindByName(userDetails.UserName) == null)
            {

                string newPassword = PasswordStore.GenerateRandomPassword(new PasswordOptions
                {
                    RequiredLength = 10,
                    RequireNonLetterOrDigit = false,
                    RequireDigit = false,
                    RequireLowercase = false,
                    RequireUppercase = false,
                    RequireNonAlphanumeric = true,
                    RequiredUniqueChars = 1
                });

                var user = new ApplicationUser
                {
                    UserName = userDetails.UserName,
                    Email = userDetails.Email,
                    EmailConfirmed = true,
                    TwoFactorEnabled = userDetails.TwoFactorEnabled,
                    PhoneNumber = userDetails.PhoneNumber,
                    PhoneNumberConfirmed = true,
                    LockoutEnabled = true,
                    FirstName = userDetails.FirstName,
                    LastName = userDetails.LastName,
                    LastPasswordChangeDate = DateTime.Now,
                    CreatedDate = DateTime.Now,
                    RecordStatus = (int)RecordStatus.Approved

                };


                var identityResult = _applicationUserManager.Create(user, newPassword);

                var result = new IdentityResult();

                if (identityResult.Succeeded)
                {
                    var findUser = _applicationUserManager.FindByName(userDetails.UserName);

                    if (!_applicationUserManager.IsInRole(findUser.Id, userRoles))
                    {
                        string[] roles = userRoles.Split(',');

                        foreach (var items in roles)
                        {

Escrow/Views/Security/CreateRole.cshtml
@model Escrow.Models.Roles
@{
    ViewBag.Title = "Create";
}

<div class="row wrapper border-bottom white-bg page-heading">
    @if (TempData["ModelError"] != null)
    {
        <div class="alert alert-danger fade in">
            <button class="close" data-dismiss="alert">
                ×
            </button>
            <i class="fa-fw fa fa-times"></i>
            <strong>Error!</strong> @TempData["ModelError"]
        </div>
    }
    <div class="col-lg-10">
        <h2></h2>
        <ol class="breadcrumb">
            <li>
                <a>Home</a>
            </li>
            <li>
                <a>Role </a>
            </li>
            <li class="active">
                <strong>Create</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Create Role</h5>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("CreateRole", "Security", FormMethod.Post, new { id = "form", @class = "wizard-big" }))
                    {
                        @*<form id="form" action="#" class="wizard-big">*@
                        <h1>Setting Details</h1>
                        <fieldset>
                            <h2>Setting Information</h2>
                            <div id="StaticSettingsOriginal" class="row">
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Name, new { @class = "control-label" })
                                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control required" })

                                    </div>
                                </div>
                            </div>

                        </fieldset>

                        <h1>Confirm Details</h1>
                        <fieldset>
                            <div id="StaticSettingsConfirm">
                            </div>
                        </fieldset>

                        @*</form>*@
                    }
                </div>
            </div>
        </div>

    </div>
</div>

@section Styles {
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
    @Styles.Render("~/plugins/wizardStepsStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/wizardSteps")
    @Scripts.Render("~/plugins/iCheck")
    @Scripts.Render("~/plugins/validate")

    <script type="text/javascript">
            $(document).ready(function () {

                $("#wizard").steps();
                $("#form").steps({
                    bodyTag: "fieldset",
                    onStepChanging: function (event, currentIndex, newIndex) {
                        // Always allow going backward even if the current step contains invalid fields!
                        if (currentIndex > newIndex) {
                            return true;
                        }

                        // If the current step is the confirmation page run the confirm method
                        if (newIndex === 1) {
                            confirm();
                        }

                        var form = $(this);

                        // Clean up if user went backward before
                        if (currentIndex < newIndex) {
                            // To remove error styles
                            $(".body:eq(" + newIndex + ") label.error", form).remove();
                            $(".body:eq(" + newIndex + ") .error", form).removeClass("error");
                        }

                        // Disable validation on fields that are disabled or hidden.
                        form.validate().settings.ignore = ":disabled,:hidden";

                        // Start validation; Prevent going forward if false
                        return form.valid();
                    },
                    onStepChanged: function (event, currentIndex, priorIndex) {
                        // Suppress (skip) "Warning" step if the user is old enough.
                        if (currentIndex === 2 && Number($("#age").val()) >= 18) {
                            $(this).steps("next");
                        }

                        // Suppress (skip) "Warning" step if the user is old enough and wants to the previous step.
                        if (currentIndex === 2 && priorIndex === 3) {
                            $(this).steps("previous");
                        }
                    },
                    onFinishing: function (event, currentIndex) {
                        var form = $(this);

                        // Disable validation on fields that are disabled.
                        // At this point it's recommended to do an overall check (mean ignoring only disabled fields)
                        form.validate().settings.ignore = ":disabled";

                        // Start validation; Prevent form submission if false
                        return form.valid();
                    },
                    onFinished: function (event, currentIndex) {
                        var form = $(this);

                        // Submit form input
                        form.submit();
                    }
                }).validate({
                    errorPlacement: function (error, element) {
                        element.before(error);
                    },
                    rules: {
                        Key: {
                            required: true,
                            maxlength: 10,
                            minlength: 2
                        }
                    }
                    //messages: {
                    //    Key: {
                    //        required: "This field is required",
                    //        maxlength: "This field only allows 10 characters",
                    //        minlength: "This field require minimumum"
                    //    }
                    //}
                });

                function confirm() {
                    $("#StaticSettingsConfirm").empty();
                    $("#StaticSettingsOriginal").clone().appendTo("#StaticSettingsConfirm");

                    //get original selects into a jq object
                    var $originalSelects = $("#StaticSettingsOriginal").find('select');

                    $("#StaticSettingsConfirm").find('select').each(function (index, item) {

                        //set new select to value of old select
                        $(item).val($originalSelects.eq(index).val());

                    });
                    $("#StaticSettingsConfirm :input").attr("disabled", true);
                }

            });
    </script>
}

Escrow/Views/Security/CreateUser.cshtml
@model Escrow.Models.UserDetails
@{
    ViewBag.Title = "Create";

    var rolesList = ViewBag.RolesList as List<SelectListItem>;

    var partnerList = ViewBag.PartnerList as List<SelectListItem>;

}

<h2></h2>

<div class="row wrapper border-bottom white-bg page-heading">
    @if (TempData["Error"] != null)
    {
        <div class="alert alert-danger fade in">
            <button class="close" data-dismiss="alert">
                ×
            </button>
            <i class="fa-fw fa fa-times"></i>
            <strong>Error!</strong> @TempData["Error"]
        </div>
    }
    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success fade in">
            <button class="close" data-dismiss="alert">
                ×
            </button>
            <i class="fa-fw fa fa-check"></i>
            <strong>Success</strong> @TempData["Success"]
        </div>
    }
    <div class="col-lg-10">
        <h2></h2>
        <ol class="breadcrumb">
            <li>
                <a>Home</a>
            </li>
            <li>
                <a>Create User  </a>
            </li>
            <li class="active">
                <strong>Create</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Create User</h5>

                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("CreateUser", "Security", FormMethod.Post, new { id = "form", @class = "wizard-big" }))
                    {
                        @*<form id="form" action="#" class="wizard-big">*@
                        <h1>Create User</h1>
                        <fieldset>
                            @*<h2>Setting Information</h2>*@
                            <div id="userOriginal">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.FirstName, new { @class = "control-label" })
                                            @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control required" })
                                            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })

                                        </div>
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.LastName, new { @class = "control-label" })
                                            @Html.TextBoxFor(model => model.LastName, new { @class = "form-control required" })
                                        </div>
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.UserName, new { @class = "control-label" })
                                            @Html.TextBoxFor(model => model.UserName, new { @class = "form-control required" })
                                            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Email, new { @class = "control-label" })
                                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control required" })
                                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.PhoneNumber, new { @class = "control-label" })
                                            @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control required" })
                                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.AssignedRole, new { @class = "control-label" })
                                            @Html.ListBoxFor(model => model.AssignedRole, rolesList, new { @class = "form-control ", required = "required" })
                                            @Html.ValidationMessageFor(model => model.AssignedRole, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        
                                    </div>

                                </div>
                            </div>
                        </fieldset>
                        <h1>Confirm Your Details</h1>
                        <fieldset>
                            <div id="userConfirm">

                            </div>
                        </fieldset>
                        @*</form>*@
                    }
                </div>
            </div>
        </div>

    </div>
</div>

@section Styles {
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
    @Styles.Render("~/plugins/wizardStepsStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/wizardSteps")
    @Scripts.Render("~/plugins/iCheck")
    @Scripts.Render("~/plugins/validate")
    <script src="~/Scripts/jquery.mask.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {

            $("#wizard").steps();
            $("#form").steps({
                bodyTag: "fieldset",
                onStepChanging: function (event, currentIndex, newIndex) {
                    // Always allow going backward even if the current step contains invalid fields!
                    if (currentIndex > newIndex) {
                        return true;
                    }

                    // Forbid suppressing "Warning" step if the user is to young
                    if (newIndex === 3 && Number($("#age").val()) < 18) {
                        return false;
                    }

                    var form = $(this);

                    // Clean up if user went backward before
                    if (currentIndex < newIndex) {
                        // To remove error styles
                        $(".body:eq(" + newIndex + ") label.error", form).remove();
                        $(".body:eq(" + newIndex + ") .error", form).removeClass("error");
                    }

                    // If the current step is the confirmation page run the confirm method
                    if (newIndex === 1) {
                        confirm();
                    }

                    // Disable validation on fields that are disabled or hidden.
                    form.validate().settings.ignore = ":disabled,:hidden";

                    // Start validation; Prevent going forward if false
                    return form.valid();
                },
                onStepChanged: function (event, currentIndex, priorIndex) {
                    // Suppress (skip) "Warning" step if the user is old enough.
                    if (currentIndex === 2 && Number($("#age").val()) >= 18) {
                        $(this).steps("next");
                    }

                    // Suppress (skip) "Warning" step if the user is old enough and wants to the previous step.
                    if (currentIndex === 2 && priorIndex === 3) {
                        $(this).steps("previous");
                    }
                },
                onFinishing: function (event, currentIndex) {
                    var form = $(this);

                    // Disable validation on fields that are disabled.
                    // At this point it's recommended to do an overall check (mean ignoring only disabled fields)
                    form.validate().settings.ignore = ":disabled";

                    // Start validation; Prevent form submission if false
                    return form.valid();
                },
                onFinished: function (event, currentIndex) {
                    var form = $(this);

                    // Submit form input
                    form.submit();
                }
            }).validate({
                errorPlacement: function (error, element) {
                    element.before(error);
                },
                rules: {
                    Name: {
                        required: true,
                        maxlength: 10,
                        minlength: 2
                    },
                    IsEnabled: {
                        required: true
                    },
                    Email: {
                        email: true
                    },
                    AssignedRole: {
                        required: true
                    },
                    PhoneNumber: {
                        required: true
                    }

                },
                messages: {
                    Name: {
                        required: "This field is required",
                        maxlength: "This field only allows 10 characters",
                        minlength: "This field require minimumum"
                    },
                    IsEnabled: {
                        required: "This field is required",
                    }
                    ,
                    Email: {
                        email: "This field require a valid email"

                    },
                    AssignedRole: {
                        required: "This Role is required"
                    },
                    PhoneNumber: {
                        required: "This Phone Number is required"
                    }
                }
                });

            function confirm() {
                //user Information Section
                $("#userConfirm").empty();
                $("#userOriginal").clone().appendTo("#userConfirm");

                //get original selects into a jq object
                var $originalSelects = $("#userOriginal").find('select');

                $("#userConfirm").find('select').each(function (index, item) {

                    //set new select to value of old select
                    $(item).val($originalSelects.eq(index).val());

                });
                $("#userConfirm :input").attr("disabled", true);

            }

        });
    </script>
}

Escrow/Views/Security/Index.cshtml
@{
    ViewBag.Title = "C2BRequests";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Roles</h2>
        <ol class="breadcrumb">
            <li>
                <a href="c">Roles</a>
            </li>
            <li>
                <a>Roles</a>
            </li>
            <li class="active">
                <strong>Index</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">

                </div>
                <div class="ibox-content">

                    <table id="Grid" class="table table-striped table-bordered table-hover" style="width:100%;">

                        <tbody>
                            <tr>
                                <td colspan="7" class="dataTables_empty">
                                    Loading data from server
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <a class="btn btn-primary btn-default" href="/security/createrole">Create Role</a>
                </div>
            </div>
        </div>
    </div>

</div>

@section Styles {
    @Styles.Render("~/Content/plugins/dataTables/dataTablesStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/dataTables")




    <script type="text/javascript">
        $(document).ready(function () {

            $('#Grid').dataTable({
                // Ajax settings
                "sPaginationType": "full_numbers",
                "bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": "@(Url.Action("Roles", "Security"))",
                 "sServerMethod": "POST",
            // Callback settings
           "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
               var EditUrl = '<a href="/security/editrole/' + aData.Id + '">' + 'Edit</a>';
               
               //$('td:eq(1)', nRow).html(EditUrl + '&nbsp;');
                return nRow;
            },
            // Display settings
                "iDisplayLength": 10,
                "aaSorting": [[0, 'desc']],
                "bJQueryUI": true,
                "aoColumns": [

                    { "mDataProp": "Name", "sTitle": "Name" },
                    //{ "mDataProp": "Commands", "sTitle": "", "bSortable": false }
                ],
                "aaSorting": [[0, 'desc']]
        });

        });

    </script>
}